# Generated by Django 3.0.4 on 2020-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200329_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='seq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
