# Generated by Django 3.0.4 on 2020-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_level_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
