# Generated by Django 3.0.4 on 2020-03-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_level_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='level',
            name='seq',
        ),
    ]
