# Generated by Django 3.0.4 on 2020-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200329_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
